# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

title: Abhiraj Mishra Homepage

background:
  image: https://cdnb.artstation.com/p/assets/images/images/006/897/659/large/mikael-gustafsson-wallpaper-mikael-gustafsson.jpg
  blur: sm # sm, md, xl... see https://tailwindcss.com/docs/backdrop-blur
  saturate: 100 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
  brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  opacity: 100 # 0-100

theme: dark
color: slate

useEqualHeights: true

layout:
  Main Systems:
    header: true
    style: row
    columns: 3
  Network:
    header: true
    style: row
    columns: 3
  Media & ARR Stack:
    header: true
    style: row
    columns: 3
  de Google:
    header: true
    style: row
    columns: 3
  Dev & Code:
    header: true
    style: row
    columns: 3